### PR TITLE
Use built-in target

### PR DESCRIPTION
**Pull request by n8henrie**
The built-in target works well and would make a reasonable default.

### CODE REVIEW

**Comment by stappersg** [comment]
There are other microcontrollors with AVR instruction set as the _atmega328p_.

**Comment by n8henrie** [comment]
Sorry, can you make the issue more concrete?

I see the benefit here being that users of a very common microcontroller don't need to explicitly set the target with a separate json file, because a functional target its now built-in to rustc. Users of other or incompatible microcontrollers can continue doing what they currently do by using a separate json config file, but the default case will be simpler.

What do you see as the downside? EDIT: In concrete terms, what current workflow or use case would break or be made more difficult than the existing situation?

**Comment by stappersg** [comment]
Make a new merge request.
Same as this MR.
The difference should be that `avr-atmega328p.json` is **not** removed.

(Karma bonus points for a more neutral commit message.)

**Comment by n8henrie** [comment]
> Make a new merge request.

Couldn't I just fix that issue within this PR?

**Comment by n8henrie** [comment]
> Karma bonus points for a more neutral commit message.

The commit message is fairly bland. Did you mean the body of the pull request (at the top of this page)? If so, I have edited that, restored the json file, and squashed the commits. Does this look okay?

**Pull request closed without merging**
